#ifndef CONFIG_H
#define CONFIG_H

/*
 *  Hardware type. Available types:
 *  ARDUINO_AVR_FEATHER32U4
 *  ARDUINO_SAMD_FEATHER_M0
 *
 *  Leave commented for autodetect
 */
//#define ARDUINO_AVR_FEATHER32U4
#define ARDUINO_PRO_MICRO
/*
 * TX or RX mode for hardware. Available types:
 * DEVICE_MODE_TX
 * DEVICE_MODE_RX
 */
//#define DEVICE_MODE_TX
#define DEVICE_MODE_RX

#define FEATURE_TX_OLED
// #define FORCE_TX_WITHOUT_INPUT

/*
 * Default mode of TX data input: SBUS
 * Possible values:
 * FEATURE_TX_INPUT_PPM
 * FEATURE_TX_INPUT_SBUS
 */
#define FEATURE_TX_INPUT_SBUS

//#define DEBUG_SERIAL
// #define DEBUG_PING_PONG
// #define DEBUG_LED

#define RADIO_FREQUENCY_BIND 915000000
#define RADIO_CHANNEL_WIDTH_BIND 125000

#define RADIO_FREQUENCY_MIN 915000000
#define RADIO_FREQUENCY_MAX 917000000
#define RADIO_FREQUENCY_RANGE (RADIO_FREQUENCY_MAX-RADIO_FREQUENCY_MIN)
#define RADIO_CHANNEL_WIDTH 250000
#define RADIO_CHANNEL_COUNT 9 // 9 channels in 2MHz range (RADIO_FREQUENCY_RANGE/RADIO_CHANNEL_WIDTH) + 1
#define RADIO_HOP_OFFSET 5

#endif
